MOBservation_strings = {
	app_name : 'MOBservation',
	loading : 'Chargement',
	ok : 'OK',
	yes : 'Oui',
	no : 'Non',
	cancel : 'Annuler',
	login_label_authentification : 'Veuillez vous authentifier sur MOBservation',
	login_input_label : 'E-mail',
	login_input_label_placeHolder : 'Entrer votre adresse e-mail',
	login_input_password : 'Password',
	login_input_password_placeHolder : 'Entrer votre mot de passe',
	login_valid : 'Valider',
	login_infos : 'Informations',
	login_error_no_email : 'Vous devez renseigner un email pour vous connecter.',
	login_error_is_not_an_email : 'Votre adresse email n\'est pas valide. Veuillez la corriger.',
	login_error_no_password : 'Vous devez renseigner un mot de passe pour vous connecter',
	login_error : 'Une erreur est survenue lors de l\'identification, veuillez réessayer ultérieurement.',
	login_information_description : '<p align="justify">L\'application MOBservation a été développée dans le cadre d\'un projet étudiant de sécurité mobile, 3<sup>ième</sup> année du cycle CSII à l\'EPSI Bordeaux.</br>Elle permet, pour un huissier français, la possibilité de créer un constat chez un client donné en prenant des photos, vidéos et en indiquant l\'adresse du constat.</br>L\'équipe de projet est composée de Frédéric BARAILLON, Jérémy DUVAL, Bastien POIUDEVAIN, Geoffrey NOEL et Guillaume ROY. </br>Pour plus d\'informations sur le développement ou le contenu de cette application, contacter Frédéric BARAILLON (<a href="mailto:f.baraillon@gmail.com">f.baraillon@gmail.com</a>)</p>',
	mobservation_disconnect  :'Déconnexion',
	mobservation_take_picture : 'Prendre une photo',
	mobservation_get_sound : 'Capturer une vidéo',
	mobservation_list_pictures : 'Liste des photos',
	mobservation_list_sounds : 'Liste des vidéos',
	mobservation_customer : 'Clients',
	mobservation_folder : 'Dossier client',
	mobservation_observations : 'Liste des anciens constats',
	mobservation_geolocation : 'Adresse du constat',
	mobservation_geolocation_label_latitude : 'Latitude',
	mobservation_geolocation_label_longitude : 'Longitude',
	mobservation_geolocation_get_location_label : 'Récupérer ma position',
	mobservation_geolocation_save_location : 'Sauvegarder',
	mobservation_geolocation_error_no_latitude_longitude : 'Vous devez d\'abord vous géolocaliser.',
	mobservation_geolocation_success_save_latitude_longitude : 'Votre position a bien été sauvegardée.',
	mobservation_observations_pictures : 'photo(s)',
	mobservation_observations_sounds : 'vidéo(s)',
	mobservation_observations_empty_text : 'Aucun ancien constat',
	mobservation_send_observation : 'Envoyer le constat',
	mobservation_welcome : 'Bienvenue sur l\'application MOBservation',
	mobservation_no_selected_customer : 'Aucun client sélectionné',
	mobservation_customer_selection : 'Vous prenez en charge le client ',
	mobservation_picture : 'Photo n° ',
	mobservation_pictures_empty_text : 'Aucune photo',
	mobservation_pictures_ask_delete_picture : 'Voulez-vous supprimer cette photo ?',
	mobservation_pictures_take_picture_successed : 'La photo a été enregistrée.',
	mobservation_sounds_take_sound_successed : 'La vidéo a été enregistré.',
	mobservation_sounds_empty_text : 'Aucune vidéo',
	mobservation_sounds_ask_delete_sound : 'Voulez-vous supprimer cette vidéo ?',
	mobservation_send_error_no_latitude_longitude : 'Vous devez d\'abord vous géolocaliser pour envoyer le constat.',
	mobservation_send_ask_title_observation : 'Titre du constat'
};